### ISSUE TITLE
Does `Instance` need a `clear` method?

### ISSUE THREAD

**Issue by drhayes** [Tjakka5/Concord#10]
When switching between maps in my world, I clear my ECS world of entities before adding new ones from the next map. What do you think about a `clear` method on `Instance` to handle such a case?

EDIT: I just realized that I could create a new instance and add all new system instances in to handle this case. Was that your intent?

**Comment by Tjakka5** [comment]
In such cases, having a new Instance would be what I had envisioned.
However, reusing the same Instance should totally be doable in my opinion, and having the functionality is nice to have as well.

Instance:clear has been added in the lastest commit.
