### ISSUE TITLE
close PRs?

### ISSUE THREAD

**Issue by ghost** [Tjakka5/Concord#27]
https://github.com/Tjakka5/Concord/pull/18 is already merged to codebase. https://github.com/Tjakka5/Concord/blob/54fbb724ab93f34b03e4bb5144337f9a43a3f70c/lib/type.lua

https://github.com/Tjakka5/Concord/pull/24 is already merged to codebase. https://github.com/Tjakka5/Concord/blob/532151d901554f3e84e42cbc9ef63329a2a7401a/README.md#ecs

**Comment by pablomayobre** [comment]
Actually #24 is not merged for some reason. But #18 is closed already.

Docs will be rewritten so there may not be a need for #24 by then. We will see
