### ISSUE TITLE
Concord.utils.loadNamespace can't deal with .DS_Store file

### ISSUE THREAD

**Issue by chicogamedev** [Tjakka5/Concord#48]
On MacOS every time a new folder is created there is a invisible file created called ".DS_Store". 

And the very useful utils "loadNamespace" is not able to ignore them and throw an error.

Solution : manually delete these files with the terminal.

I know nothing in Regex but the bug should be easily fixed.

**Comment by pablomayobre** [comment]
This is now fixed on experimental, but I would love it if you could test and report back.

Also I think there may be similar issues when passing a table with file paths, but that is most likely the user's fault.

**Comment by chicogamedev** [comment]
Thanks amazing ! It works great now. 😃
