### ISSUE TITLE
Using Concord on other sdk/engines

### ISSUE THREAD

**Issue by cemuka** [Tjakka5/Concord#56]
How can I use on other platforms? I'd like to use it in Playdate SDK(Lua).

**Comment by pablomayobre** [comment]
You just can, Concord is not tied to Lua except for `Utils.loadNamespace` which you could implement yourself for your particular use case.

Concord was thought out with LuaJIT in mind, but it should be fairly compatible with Lua 5.1 and may be compatible with other versions, but it's entirely untested.

**Comment by cemuka** [comment]
Seems like playdate does not allow `require`, only `import`. Otherwise I'll try what I can do, thanks for the answer.

**Comment by pablomayobre** [comment]
Well, then it's not running Lua but a Lua-like language. That's similar to PICO8 does, and you can't expect Lua libraries to be entirely compatible with it.

Too bad, I guess forking is your best choice. Maybe reimplement and polyfill `require` on top of `import`?

**Comment by cemuka** [comment]
Yeah like you said, I need to implement a platform specific version for playdate. Thanks for a good ecs library and help :)
